- hosts: localhost
  become: false
  gather_facts: false
  tasks:

  # Create variables files for images and VMs
  - name: Create Variable Files
    include_role:
      name: create_variables_file
    vars:
      variable_name: '{{item}}'
    loop:
      '{{variable_files}}'

- hosts: pvenodes
  become: true
  gather_facts: false

- hosts: pvenodes[0]
  become: false
  gather_facts: false

 
