---
- name: install pip3
  apt: name=python3-pip state=present 
  
- name: Create VM in Proxmox
  hosts: pvenodes
  gather_facts: no

  vars_prompt:
    - name: vm_name
      prompt: "Enter the name for the new VM:"
    - name: proxmox_node
      prompt: "Enter the Proxmox node to use:"

  vars:
    proxmox_host: 10.131.9.159
    proxmox_user: "root"
    proxmox_password: "root14"
    vm_id: 9000  # Adjust as needed

  tasks:
    - name: Install proxmoxer library
      pip:
        name: proxmoxer
        state: present

    - name: Create VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        ostemplate: "local:iso/debian-10.0-standard_10.0-1_amd64.iso"
        memory: "512"
        cores: "1"
        net0: "virtio,bridge=vmbr0"
        disk0: "vm:16,size=8G"
        state: "present"
