- name: Create VM in Proxmox
  hosts: pvenodes
  gather_facts: no

  vars_prompt:
    - name: vm_name
      prompt: "Enter the name for the new VM:"
    - name: proxmox_node
      prompt: "Enter the Proxmox node to use:"

  vars:
    proxmox_host: 10.131.9.159
    proxmox_user: "root"
    proxmox_password: "root14"
    vm_id: 9000  # Adjust as needed

  tasks:
    - name: Install python3-pip
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: yes

    - name: Install proxmoxer library
      ansible.builtin.pip:
        name: proxmoxer
        state: present
      become: yes

    - name: Create VM
      ansible.builtin.uri:
        url: "https://{{ proxmox_host }}/api2/json/nodes/{{ proxmox_node }}/qemu"
        method: POST
        headers:
          Content-Type: "application/json"
        user: "{{ proxmox_user }}"
        password: "{{ proxmox_password }}"
        body_format: json
        body: |
          {
            "vmid": "{{ vm_id }}",
            "name": "{{ vm_name }}",
            "ostype": "l26", 
            "ide2": "local:iso/debian-10.0-standard_10.0-1_amd64.iso,media=cdrom",
            "sockets": "1",
            "cores": "1",
            "memory": "512",
            "net0": "virtio,bridge=vmbr0",
            "virtio0": "vm:16,format=qcow2,size=8G"
          }
        status_code: 201
