
- name: Create admin user
  hosts: pvenodes
  become: true
  become_user: root
  tasks: 
    - name: Admin user
      ansible.builtin.user: 
        name: admin
        password: "{{ 'password' | password_hash('sha512', 'root') }}"
        state: present
        shell: "/bin/bash"
        generate_ssh_key: true
