---
- name: Create Virtual Machine on Proxmox
  hosts: rh
  gather_facts: no
  vars_prompt:
    - name: proxmox_node
      prompt: "Enter the Proxmox node to use"
    - name: vm_name
      prompt: "Enter the name for the new VM"
    - name: proxmox_host
      prompt: "Enter the Proxmox server IP or hostname"
    - name: proxmox_user
      prompt: "Enter the Proxmox username"
    - name: proxmox_password
      prompt: "Enter the Proxmox password"
      private: yes  # Masking the password input
    - name: vm_id
      prompt: "Enter the VM ID"

  vars:
    api_host: 10.131.9.130
    api_user: root@pam
    api_password: root14
    ansible_user: root
    ansible_password: root14
    ansible_ssh_pass: root14
    

  tasks:
    - name: Convert vm_id to integer
      set_fact:
        vmid_int: "{{ vm_id | int }}"

    - name: Create VM on Proxmox
      community.general.proxmox_kvm:
        api_host: 10.131.9.140
        api_user: root@pam
        api_password: root14
        node: rh
        vmid: "603"
        state: present
      register: vm_creation_result

    - name: Print VM creation result
      debug:
        var: vm_creation_result
