---
- name: Create Virtual Machine on Proxmox
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: proxmox_node
      prompt: "Enter the Proxmox node to use"
    - name: vm_name
      prompt: "Enter the name for the new VM"
    - name: os_template
      prompt: "Enter the name or ID of the OS template on the local Proxmox server"
    - name: proxmox_host
      prompt: "Enter the Proxmox server IP or hostname"
    - name: proxmox_user
      prompt: "Enter the Proxmox username"
    - name: proxmox_password
      prompt: "Enter the Proxmox password"
      private: yes  # Masking the password input

  vars:
    ansible_user: root 
    ansible_ssh_pass: root14 

  tasks:
    - name: Create VM on Proxmox
      proxmox_kvm:
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_name }}"
        hostname: "{{ vm_name }}"
        password: "{{ proxmox_password }}"
        username: "{{ proxmox_user }}"
        ostemplate: "{{ os_template }}"
        state: present
      register: vm_creation_result

    - name: Print VM creation result
      debug:
        var: vm_creation_result
